### ISSUE TITLE
Manual doesn't start: 

### ISSUE THREAD

**Issue by starquake** [IDemiurge/Eidolons#99]
When I click "Manual" the screen looks like this:
![image](https://user-images.githubusercontent.com/1044544/59143872-db2e7000-89cf-11e9-982d-cfb37418112e.png)

This is what shows up in the log window:

```
java.lang.ArrayIndexOutOfBoundsException: 1
        at eidolons.libgdx.gui.menu.selection.manual.ManualPanel.createListData(ManualPanel.java:43)
        at eidolons.libgdx.gui.menu.selection.SelectionPanel.init(SelectionPanel.java:181)
        at eidolons.libgdx.gui.menu.selection.SelectionPanel.<init>(SelectionPanel.java:94)
        at eidolons.libgdx.gui.menu.selection.SelectionPanel.<init>(SelectionPanel.java:50)
        at eidolons.libgdx.gui.menu.selection.manual.ManualPanel.<init>(ManualPanel.java:24)
        at eidolons.libgdx.screens.ScreenWithVideoLoader$1.<init>(ScreenWithVideoLoader.java:126)
        at eidolons.libgdx.screens.ScreenWithVideoLoader.lambda$preLoad$7(ScreenWithVideoLoader.java:126)
        at main.system.GuiEventManagerImpl.lambda$trigger_$2(GuiEventManagerImpl.java:145)
        at main.system.GuiEventManagerImpl.processEvents_(GuiEventManagerImpl.java:169)
        at main.system.GuiEventManagerImpl.processEvents(GuiEventManagerImpl.java:57)
        at main.system.GuiEventManager.processEvents(GuiEventManager.java:71)
        at eidolons.libgdx.launch.GenericLauncher.render_(GenericLauncher.java:250)
        at eidolons.libgdx.launch.GenericLauncher.render(GenericLauncher.java:246)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
```

**Comment by IDemiurge** [comment]
That version wasn't supposed to support in-game manual, just forgot to remove it from menu. Thanks for the log though!
